name: mgr
channels:
  - defaults
  - bioconda
  - daler
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - amply=0.1.6
  - appdirs=1.4.4
  - argparse-dataclass=2.0.0
  - attmap=0.13.2
  - attrs=23.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - cni=1.0.1
  - cni-plugins=1.3.0
  - coin-or-cbc=2.10.10
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.8
  - coin-or-utils=2.11.9
  - coincbc=2.10.10
  - colorama=0.4.6
  - conda-inject=1.3.1
  - configargparse=1.7
  - connection_pool=0.0.3
  - datrie=0.8.2
  - docutils=0.20.1
  - dpath=2.1.6
  - eido=0.2.2
  - exceptiongroup=1.2.0
  - gitdb=4.0.11
  - gitpython=3.1.41
  - humanfriendly=10.0
  - icu=73.2
  - idna=3.6
  - immutables=0.20
  - importlib_resources=6.1.1
  - iniconfig=2.0.0
  - jinja2=3.1.3
  - jq=1.7.1
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jupyter_core=5.7.1
  - ld_impl_linux-64=2.40
  - libarchive=3.5.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.26
  - libseccomp=2.4.4
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.12.5
  - libzlib=1.2.13
  - logmuse=0.2.6
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - nbformat=5.9.2
  - ncurses=6.4
  - numpy=1.26.4
  - oniguruma=6.9.9
  - openssl=3.2.1
  - packaging=23.2
  - pandas=2.2.0
  - peppy=0.40.1
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.2
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - psutil=5.9.8
  - pulp=2.8.0
  - pygments=2.17.2
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - pytest=8.0.0
  - python=3.12.1
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-tzdata=2023.4
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - readline=8.2
  - referencing=0.33.0
  - requests=2.31.0
  - reretry=0.11.8
  - rich=13.7.0
  - rpds-py=0.17.1
  - setuptools=69.0.3
  - singularity=3.8.6
  - six=1.16.0
  - slack-sdk=3.26.2
  - slack_sdk=3.26.2
  - smart_open=6.4.0
  - smmap=5.0.0
  - snakemake=8.4.8
  - snakemake-interface-common=1.15.3
  - snakemake-interface-executor-plugins=8.2.0
  - snakemake-interface-storage-plugins=3.0.0
  - snakemake-minimal=8.4.8
  - squashfs-tools=4.6.1
  - stopit=1.1.2
  - tabulate=0.9.0
  - throttler=1.2.2
  - tk=8.6.13
  - tomli=2.0.1
  - toposort=1.10
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzdata=2024a
  - ubiquerg=0.7.0
  - urllib3=2.2.0
  - veracitools=0.1.3
  - wheel=0.42.0
  - wrapt=1.16.0
  - xz=5.2.6
  - yaml=0.2.5
  - yte=1.5.4
  - zipp=3.17.0
  - zstd=1.5.5
