#!/bin/sh

# This script allows for multiple structure alignment
# of homologs acquired by running get_homologs
#
# !!! Adding USalign location to $PATH is required !!!

mkdir data/$1/alignment -p
USalign -dir data/$1/structures/ data/$1/list.txt -suffix .pdb -mm 4 -het 0 \
		-o data/$1/alignment/sup > data/$1/alignment/alignment.log
# awk -i inplace 'if($1 == "ATOM") {print $0}' data/$1/alignment/sup.*.pdb

