cores: 12
jobs: 4
restart-times: 1
latency-wait: 60
show-failed-logs: True
printshellcmds: True

# DO NOT change the following settings
snakefile: workflow/Snakefile
nolock: True
use-conda: True
keep-going: True
conda-frontend: conda
use-singularity: True
rerun-incomplete: True
