snakefile: workflow/Snakefile
cores: 12
rerun-incomplete: True
use-singularity: True
use-conda: True
conda-frontend: conda
latency-wait: 60
show-failed-logs: True
keep-going: True
printshellcmds: True
restart-times: 3