email: "your@email.com"
send_email: False

USalign:
  split: 0
  full: "T"

blastp:
  database: "swissprot"
  matrix: "BLOSUM62"
  e_value: 1e-20
  word_size: 6
  max_target_seqs: 10
  additional_args: ""

tblastn:
  database: "refseq_select_rna"
  matrix: "BLOSUM62"
  e_value: 1e-20
  word_size: 6
  max_target_seqs: 10
  additional_args: ""

split_long_nucleotide_sequences:
  threshold: -1
  chunk_size: -1

RNAalifold: "-p -r -d2 --noLP --color --aln"
RNAfold: "-p -d2 --noLP"

plots:
  DPI: 300