email: your@email.com
send_email: False
split_long_nucleotide_sequences:
  threshold: -1
  chunk_size: -1
RNAalifold: -p -r -d2 --noLP --color --aln
RNAfold: -p -d2 --noLP
blast:
  e_value: 1e-100
  outfmt: 6
USalign:
  split: 0
  full: T
plots:
  DPI: 300