email: your@email.com
send_email: False
split_long_nucleotide_sequences:
  threshold: 3000
  chunk_size: 1500
RNAalifold: -p -r -d2 --noLP --color --aln
RNAfold: -p -d2 --noLP
blast:
  e_value: 1e-100
  outfmt: 6
USalign: # see USalign -h
  split: 0
  full: T
plots:
  DPI: 300