#!/bin/bash

# This script allows for getting all the structural
# homologs for a given PDB ID based on SCOPe

if [ -z $1 ]; then
	printf "\nUsage:\n\t./get_homologs <PDB_ID>\n"
	exit 1
fi

category=$(cat dir.cla.scope.2.08-stable.tsv | grep $1 | awk '{print $4}' | awk '!seen[$0]++')
homologs=$(cat dir.cla.scope.2.08-stable.tsv | grep $category | awk '{print $2}' | awk '!seen[$0]++')
mkdir data/$1/seq -p
mkdir data/$1/str -p
for e in $homologs; do
	echo $e >> ../data/$1/list.txt
	wget https://www.rcsb.org/fasta/entry/$e -O ../data/$1/seq/$e.fasta
	wget https://files.rcsb.org/download/$e.pdb -O ../data/$1/str/$e.pdb
done
